spring:
  application:
    name: user-greeting-service

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

app:
  greetingService:
    serviceId: greeting-service
    endpoint:
      greeting: /greeting