spring:
  application:
    name: user-greeting-service

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

app:
  greetingService:
    serviceId: greeting-service
    endpoint:
      greeting: /greeting

greeting-service:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 15000